from langgraph.graph import StateGraph, END
import ollama

class NavState(dict):
    current_beacon: str
    destination: str
    direction: str | None

def build_nav_graph(node):

    #llm = Ollama(model="qwen2.5:0.5b", temperature=0.1)

    graph = StateGraph(NavState)

    map = """
    Map of tunnels:
    ,Loeb,Southam,TunnelJunction,Library,Azrieli/Tory,Steacie,Richcraft,UC,Canal,Nicol,Mackenzie/Minto,Frontenac,ResComms,CTTC,Robertson
    Loeb1,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_LEFT,NAV_LEFT,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Loeb2,NAV_DOCK,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_U-TURN,NAV_U-TURN,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT
    Southam1,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_PASS,NAV_PASS,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Southam3,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_PASS,NAV_U-TURN,NAV_U-TURN,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    TunnelJunction1,NAV_RIGHT,NAV_RIGHT,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    TunnelJunction2,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT
    TunnelJunction4,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT
    Library2,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Library3,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT
    Azrieli/Tory1,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Azrieli/Tory3,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    Azrieli/Tory4,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT
    Steacie1,NAV_RIGHT,NAV_RIGHT,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Steacie3,NAV_LEFT,NAV_LEFT,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    Steacie4,NAV_U-TURN,NAV_U-TURN,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_DOCK,NAV_RIGHT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT
    Richcraft1,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    UC1,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    UC3,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    UC4,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_RIGHT,NAV_RIGHT,NAV_DOCK,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT
    Canal2,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN
    Canal4,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS
    Nicol1,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_LEFT,NAV_LEFT
    Nicol2,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_U-TURN,NAV_U-TURN
    Nicol4,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_RIGHT,NAV_RIGHT
    Mackenzie/Minto1,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_U-TURN,NAV_PASS,NAV_PASS
    Mackenzie/Minto3,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_PASS,NAV_U-TURN,NAV_U-TURN
    Frontenac1,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_U-TURN,NAV_PASS,NAV_PASS
    Frontenac3,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_PASS,NAV_U-TURN,NAV_U-TURN
    ResComms1,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK,NAV_PASS,NAV_PASS
    ResComms3,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_U-TURN,NAV_U-TURN
    CTTC1,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_RIGHT,NAV_DOCK,NAV_PASS
    CTTC3,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_LEFT,NAV_DOCK,NAV_U-TURN
    CTTC4,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_U-TURN,NAV_DOCK,NAV_RIGHT
    Robertson1,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_PASS,NAV_DOCK
    """

    def decide_direction(state: NavState):
        prompt = f"""
        The robot is currently at beacon {state["current_beacon"]} and needs to go to {state["destination"]}. 
        Below is a map of the tunnels with the required navigation action to get from each beacon (rows) to each other beacon (columns). The robot can only take one action at a time, and must follow the actions in the map to navigate correctly.
        {map}
        What direction should it take next from the following list of options based on the current state and map of the tunnels?:
        - NAV_LEFT
        - NAV_RIGHT
        - NAV_PASS
        - NAV_U-TURN
        - NAV_DOCK
        Provide only one of these directions as the output.
        """
        node.get_logger().info("***************PROMPTING LLM FOR DIRECTION DECISION...******************")
        node.get_logger().info(f"Prompt to LLM: {prompt}")

        response = ollama.generate(
            model='gemma3:1b',
            prompt=prompt
        )

        node.get_logger().info(f"Raw LLM Response: {response}")

        # Extract only the first token-like output, in case model returns explanation
        result = response["response"].strip().split()[0]

        node.get_logger().info(f"LLM Response: {result}")

        state["direction"] = result
        return state

    
    graph.add_node("Decide Direction", decide_direction)
    graph.set_entry_point("Decide Direction")
    graph.add_edge("Decide Direction", END)

    return graph.compile()

if __name__ == "__main__":
    pass